//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeAnalyzeWPF.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CodeAnalyzeWPF.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1_a {
            get {
                object obj = ResourceManager.GetObject("_1_a", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1_b {
            get {
                object obj = ResourceManager.GetObject("_1_b", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _2_a {
            get {
                object obj = ResourceManager.GetObject("_2_a", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _2_b {
            get {
                object obj = ResourceManager.GetObject("_2_b", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _3_a {
            get {
                object obj = ResourceManager.GetObject("_3_a", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _3_b {
            get {
                object obj = ResourceManager.GetObject("_3_b", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _4_a {
            get {
                object obj = ResourceManager.GetObject("_4_a", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _4_b {
            get {
                object obj = ResourceManager.GetObject("_4_b", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _5_a {
            get {
                object obj = ResourceManager.GetObject("_5_a", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _5_b {
            get {
                object obj = ResourceManager.GetObject("_5_b", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap btn_upload_bg {
            get {
                object obj = ResourceManager.GetObject("btn_upload_bg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap img_line_01 {
            get {
                object obj = ResourceManager.GetObject("img_line_01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap merge {
            get {
                object obj = ResourceManager.GetObject("merge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap person {
            get {
                object obj = ResourceManager.GetObject("person", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap personmask {
            get {
                object obj = ResourceManager.GetObject("personmask", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2018-12-31 00:00:24.
        /// </summary>
        internal static string PreloadTime01 {
            get {
                return ResourceManager.GetString("PreloadTime01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2019-01-18 00:00:50.
        /// </summary>
        internal static string PreloadTime02 {
            get {
                return ResourceManager.GetString("PreloadTime02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2018-12-14 08:00:00.
        /// </summary>
        internal static string PreloadTime03 {
            get {
                return ResourceManager.GetString("PreloadTime03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2019-02-01 00:05:00.
        /// </summary>
        internal static string PreloadTime04 {
            get {
                return ResourceManager.GetString("PreloadTime04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2019-01-05 00:08:00.
        /// </summary>
        internal static string PreloadTime05 {
            get {
                return ResourceManager.GetString("PreloadTime05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2018-11-29 09:00:00.
        /// </summary>
        internal static string PreloadTime06 {
            get {
                return ResourceManager.GetString("PreloadTime06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2019-01-01 00:00:00.
        /// </summary>
        internal static string PreloadTime07 {
            get {
                return ResourceManager.GetString("PreloadTime07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2019-01-01 00:20:00.
        /// </summary>
        internal static string PreloadTime08 {
            get {
                return ResourceManager.GetString("PreloadTime08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2019-01-01 00:41:00.
        /// </summary>
        internal static string PreloadTime09 {
            get {
                return ResourceManager.GetString("PreloadTime09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2019-01-01 05:05:00.
        /// </summary>
        internal static string PreloadTime10 {
            get {
                return ResourceManager.GetString("PreloadTime10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2019-01-01 12:00:00.
        /// </summary>
        internal static string PreloadTime11 {
            get {
                return ResourceManager.GetString("PreloadTime11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PHP Analyse.
        /// </summary>
        internal static string PreloadTitle01 {
            get {
                return ResourceManager.GetString("PreloadTitle01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C Analtse.
        /// </summary>
        internal static string PreloadTitle02 {
            get {
                return ResourceManager.GetString("PreloadTitle02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C++ Analyse.
        /// </summary>
        internal static string PreloadTitle03 {
            get {
                return ResourceManager.GetString("PreloadTitle03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ruby Analyse.
        /// </summary>
        internal static string PreloadTitle04 {
            get {
                return ResourceManager.GetString("PreloadTitle04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pythin Analyse.
        /// </summary>
        internal static string PreloadTitle05 {
            get {
                return ResourceManager.GetString("PreloadTitle05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C# Analyse.
        /// </summary>
        internal static string PreloadTitle06 {
            get {
                return ResourceManager.GetString("PreloadTitle06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JavaScript Analyse.
        /// </summary>
        internal static string PreloadTitle07 {
            get {
                return ResourceManager.GetString("PreloadTitle07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BOCOL Analyse.
        /// </summary>
        internal static string PreloadTitle08 {
            get {
                return ResourceManager.GetString("PreloadTitle08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PowerShell Analyse.
        /// </summary>
        internal static string PreloadTitle09 {
            get {
                return ResourceManager.GetString("PreloadTitle09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bash Analyse.
        /// </summary>
        internal static string PreloadTitle10 {
            get {
                return ResourceManager.GetString("PreloadTitle10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haskell Analyse.
        /// </summary>
        internal static string PreloadTitle11 {
            get {
                return ResourceManager.GetString("PreloadTitle11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap setting {
            get {
                object obj = ResourceManager.GetObject("setting", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap settingmask {
            get {
                object obj = ResourceManager.GetObject("settingmask", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap test {
            get {
                object obj = ResourceManager.GetObject("test", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap testmask {
            get {
                object obj = ResourceManager.GetObject("testmask", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 我不是.
        /// </summary>
        internal static string UPD01 {
            get {
                return ResourceManager.GetString("UPD01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 我没有.
        /// </summary>
        internal static string UPD02 {
            get {
                return ResourceManager.GetString("UPD02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 别瞎说.
        /// </summary>
        internal static string UPD03 {
            get {
                return ResourceManager.GetString("UPD03", resourceCulture);
            }
        }
    }
}
